# Generated by Django 3.0 on 2019-12-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191213_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время пробное'),
        ),
    ]
