# Generated by Django 3.0 on 2020-01-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('f1b9', 'Попутчик'), ('f007', 'Водитель')], default='m', help_text='Book availability', max_length=4),
        ),
    ]
