# Generated by Django 3.0 on 2020-01-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('f1b9', 'Попутчик'), ('f007', 'Водитель')], default='f1b9', help_text='Book availability', max_length=4),
        ),
    ]
