# Generated by Django 3.0 on 2020-01-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200112_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('<i class="fas fa-car"></i>', 'Попутчик'), ('<i class="fas fa-user"></i>', 'Водитель')], default='f1b9', help_text='Book availability', max_length=28),
        ),
    ]
